apiVersion: v1
kind: Service
metadata:
  name: "wikijs"
  namespace: ns-wiki
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: "wikijs"