kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiki-pv-claim
  namespace: ns-wiki
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi